events {}

http {
    upstream shortener {
        server shortener-service:8000;
    }

    upstream redirector {
        server redirect-service:8000;
    }

    server {
        listen 80;

        location /shorten {
            proxy_pass http://shortener;
        }

        location /stats/ {
            proxy_pass http://shortener;
        }

        location /internal/ {
            proxy_pass http://shortener;
        }

        location / {
            proxy_pass http://redirector;
        }
    }
}
